<?php
/**
 * Created by PhpStorm.
 * User: JHR
 * Date: 2019/10/20
 * Time: 10:44
 */
namespace app\index\controller;

use think\Controller;

class Base extends Controller {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


}